// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.ws.addressing.action;


public class ActionEndpoint_bar_ResponseStruct {
    protected java.lang.String result;
    
    public ActionEndpoint_bar_ResponseStruct() {
    }
    
    public ActionEndpoint_bar_ResponseStruct(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
