//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.06 at 02:11:05 PM CET 
//


package org.jboss.rs.model.dd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jboss.rs.model.dd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Jbossrs_QNAME = new QName("http://org.jboss.rs/", "jbossrs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jboss.rs.model.dd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link JbossrsType }
     * 
     */
    public JbossrsType createJbossrsType() {
        return new JbossrsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JbossrsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org.jboss.rs/", name = "jbossrs")
    public JAXBElement<JbossrsType> createJbossrs(JbossrsType value) {
        return new JAXBElement<JbossrsType>(_Jbossrs_QNAME, JbossrsType.class, null, value);
    }

}
