//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/xml">http://java.sun.com/xml/xml</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.06 at 02:11:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org.jboss.rs/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jboss.rs.model.dd;
