// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jsr181.complex.client;

public interface RegistrationService extends java.rmi.Remote {
    public long[] bulkRegister(org.jboss.test.ws.jsr181.complex.client.Customer[] customers, java.util.Calendar when) throws 
        org.jboss.test.ws.jsr181.complex.client.AlreadyRegisteredException, org.jboss.test.ws.jsr181.complex.client.ValidationException,  java.rmi.RemoteException;
    public org.jboss.test.ws.jsr181.complex.client.Statistics getStatistics(org.jboss.test.ws.jsr181.complex.client.Customer customer) throws 
         java.rmi.RemoteException;
    public long register(org.jboss.test.ws.jsr181.complex.client.Customer customer, java.util.Calendar when) throws 
        org.jboss.test.ws.jsr181.complex.client.ValidationException, org.jboss.test.ws.jsr181.complex.client.AlreadyRegisteredException,  java.rmi.RemoteException;
    public boolean registerForInvoice(org.jboss.test.ws.jsr181.complex.client.InvoiceCustomer invoiceCustomer) throws 
        org.jboss.test.ws.jsr181.complex.client.ValidationException, org.jboss.test.ws.jsr181.complex.client.AlreadyRegisteredException,  java.rmi.RemoteException;
}
