// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.addressing.replyto;


public class ReplyToEndpoint_addItemResponse_RequestStruct {
    protected java.lang.String result;
    
    public ReplyToEndpoint_addItemResponse_RequestStruct() {
    }
    
    public ReplyToEndpoint_addItemResponse_RequestStruct(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
