// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class BaseDataTypesDocLitWService_SerializerRegistry implements SerializerConstants {
    public BaseDataTypesDocLitWService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://tempuri.org/", "RetObject");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObject_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObject.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDecimal");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimal_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimal.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetSByte");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByte_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByte.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetBool");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBool_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBool.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetShort");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShort_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShort.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetByteArrayResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDateTimeResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetULong");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULong_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULong.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUriResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetTimeSpanResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetBoolResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetQNameResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDouble");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDouble_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDouble.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDateTime");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTime_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTime.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetSingle");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingle_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingle.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetStringResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralFragmentSerializer(SchemaConstants.QNAME_TYPE_URTYPE, NOT_NULLABLE, "");
            registerSerializer(mapping2,javax.xml.soap.SOAPElement.class, SchemaConstants.QNAME_TYPE_URTYPE, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetGuidResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetLong");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLong_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLong.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetLongResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUInt");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUInt_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUInt.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetULongResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUIntResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetChar");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetChar_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetChar.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(SchemaConstants.QNAME_TYPE_BASE64_BINARY,
                "", XSDBase64BinaryEncoder.getInstance());
            registerSerializer(mapping2,byte[].class, SchemaConstants.QNAME_TYPE_BASE64_BINARY, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetByte");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByte_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByte.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUShortResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetCharResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetSByteResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetTimeSpan");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpan_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpan.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetByteArray");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArray_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArray.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetString");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetString_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetString.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetObjectResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUri");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUri_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUri.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetQName");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQName_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQName.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetFloatResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetUShort");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShort_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShort.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDoubleResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetByteResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetFloat");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloat_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloat.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetSingleResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetIntResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetShortResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetInt");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetInt_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetInt.class, type, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetGuid");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuid_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuid.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(SchemaConstants.QNAME_TYPE_ANY_URI,
                "", XSDAnyURIEncoder.getInstance());
            registerSerializer(mapping2,java.net.URI.class, SchemaConstants.QNAME_TYPE_ANY_URI, serializer);
        }
        {
            QName type = new QName("http://tempuri.org/", "RetDecimalResponse");
            CombinedSerializer serializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
