// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class IBaseDataTypesDocLitW_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.IBaseDataTypesDocLitW {
    
    
    
    /*
     *  public constructor
     */
    public IBaseDataTypesDocLitW_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://131.107.72.15/SoapWsdl_BaseDataTypes_XmlFormatter_Service_Indigo/BaseDataTypesDocLitW.svc");
    }
    
    
    /*
     *  implementation of retDateTime
     */
    public java.util.Calendar retDateTime(java.util.Calendar inDateTime)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetDateTime_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTime _myRetDateTime = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTime();
            _myRetDateTime.setInDateTime(inDateTime);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetDateTime_RetDateTime_QNAME);
            _bodyBlock.setValue(_myRetDateTime);
            _bodyBlock.setSerializer(ns1_myRetDateTime_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetDateTime");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse)_responseObj;
            }
            
            return _result.getRetDateTimeResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retSByte
     */
    public java.lang.Byte retSByte(java.lang.Byte inSByte)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetSByte_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByte _myRetSByte = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByte();
            _myRetSByte.setInSByte(inSByte);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetSByte_RetSByte_QNAME);
            _bodyBlock.setValue(_myRetSByte);
            _bodyBlock.setSerializer(ns1_myRetSByte_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetSByte");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse)_responseObj;
            }
            
            return _result.getRetSByteResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retFloat
     */
    public java.lang.Float retFloat(java.lang.Float inFloat)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetFloat_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloat _myRetFloat = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloat();
            _myRetFloat.setInFloat(inFloat);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetFloat_RetFloat_QNAME);
            _bodyBlock.setValue(_myRetFloat);
            _bodyBlock.setSerializer(ns1_myRetFloat_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetFloat");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse)_responseObj;
            }
            
            return _result.getRetFloatResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retBool
     */
    public java.lang.Boolean retBool(java.lang.Boolean inBool)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetBool_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBool _myRetBool = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBool();
            _myRetBool.setInBool(inBool);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetBool_RetBool_QNAME);
            _bodyBlock.setValue(_myRetBool);
            _bodyBlock.setSerializer(ns1_myRetBool_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetBool");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse)_responseObj;
            }
            
            return _result.getRetBoolResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retShort
     */
    public java.lang.Short retShort(java.lang.Short inShort)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetShort_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShort _myRetShort = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShort();
            _myRetShort.setInShort(inShort);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetShort_RetShort_QNAME);
            _bodyBlock.setValue(_myRetShort);
            _bodyBlock.setSerializer(ns1_myRetShort_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetShort");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse)_responseObj;
            }
            
            return _result.getRetShortResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retDecimal
     */
    public java.math.BigDecimal retDecimal(java.math.BigDecimal inDecimal)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetDecimal_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimal _myRetDecimal = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimal();
            _myRetDecimal.setInDecimal(inDecimal);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetDecimal_RetDecimal_QNAME);
            _bodyBlock.setValue(_myRetDecimal);
            _bodyBlock.setSerializer(ns1_myRetDecimal_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetDecimal");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse)_responseObj;
            }
            
            return _result.getRetDecimalResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retUShort
     */
    public int retUShort(int inUShort)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetUShort_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShort _myRetUShort = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShort();
            _myRetUShort.setInUShort(inUShort);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetUShort_RetUShort_QNAME);
            _bodyBlock.setValue(_myRetUShort);
            _bodyBlock.setSerializer(ns1_myRetUShort_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetUShort");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse)_responseObj;
            }
            
            return _result.getRetUShortResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retByteArray
     */
    public byte[] retByteArray(byte[] inByteArray)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetByteArray_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArray _myRetByteArray = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArray();
            _myRetByteArray.setInByteArray(inByteArray);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetByteArray_RetByteArray_QNAME);
            _bodyBlock.setValue(_myRetByteArray);
            _bodyBlock.setSerializer(ns1_myRetByteArray_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetByteArray");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse)_responseObj;
            }
            
            return _result.getRetByteArrayResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retString
     */
    public java.lang.String retString(java.lang.String inString)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetString_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetString _myRetString = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetString();
            _myRetString.setInString(inString);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetString_RetString_QNAME);
            _bodyBlock.setValue(_myRetString);
            _bodyBlock.setSerializer(ns1_myRetString_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetString");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse)_responseObj;
            }
            
            return _result.getRetStringResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retDouble
     */
    public java.lang.Double retDouble(java.lang.Double inDouble)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetDouble_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDouble _myRetDouble = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDouble();
            _myRetDouble.setInDouble(inDouble);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetDouble_RetDouble_QNAME);
            _bodyBlock.setValue(_myRetDouble);
            _bodyBlock.setSerializer(ns1_myRetDouble_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetDouble");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse)_responseObj;
            }
            
            return _result.getRetDoubleResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retULong
     */
    public java.math.BigInteger retULong(java.math.BigInteger inULong)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetULong_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULong _myRetULong = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULong();
            _myRetULong.setInULong(inULong);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetULong_RetULong_QNAME);
            _bodyBlock.setValue(_myRetULong);
            _bodyBlock.setSerializer(ns1_myRetULong_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetULong");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse)_responseObj;
            }
            
            return _result.getRetULongResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retTimeSpan
     */
    public java.lang.String retTimeSpan(java.lang.String inTimeSpan)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetTimeSpan_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpan _myRetTimeSpan = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpan();
            _myRetTimeSpan.setInTimeSpan(inTimeSpan);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetTimeSpan_RetTimeSpan_QNAME);
            _bodyBlock.setValue(_myRetTimeSpan);
            _bodyBlock.setSerializer(ns1_myRetTimeSpan_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetTimeSpan");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse)_responseObj;
            }
            
            return _result.getRetTimeSpanResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retUri
     */
    public java.net.URI retUri(java.net.URI inUri)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetUri_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUri _myRetUri = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUri();
            _myRetUri.setInUri(inUri);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetUri_RetUri_QNAME);
            _bodyBlock.setValue(_myRetUri);
            _bodyBlock.setSerializer(ns1_myRetUri_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetUri");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse)_responseObj;
            }
            
            return _result.getRetUriResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retChar
     */
    public java.lang.Integer retChar(java.lang.Integer inChar)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetChar_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetChar _myRetChar = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetChar();
            _myRetChar.setInChar(inChar);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetChar_RetChar_QNAME);
            _bodyBlock.setValue(_myRetChar);
            _bodyBlock.setSerializer(ns1_myRetChar_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetChar");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse)_responseObj;
            }
            
            return _result.getRetCharResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retGuid
     */
    public java.lang.String retGuid(java.lang.String inGuid)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetGuid_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuid _myRetGuid = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuid();
            _myRetGuid.setInGuid(inGuid);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetGuid_RetGuid_QNAME);
            _bodyBlock.setValue(_myRetGuid);
            _bodyBlock.setSerializer(ns1_myRetGuid_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetGuid");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse)_responseObj;
            }
            
            return _result.getRetGuidResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retObject
     */
    public javax.xml.soap.SOAPElement retObject(javax.xml.soap.SOAPElement inObject)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetObject_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObject _myRetObject = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObject();
            _myRetObject.setInObject(inObject);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetObject_RetObject_QNAME);
            _bodyBlock.setValue(_myRetObject);
            _bodyBlock.setSerializer(ns1_myRetObject_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetObject");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse)_responseObj;
            }
            
            return _result.getRetObjectResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retByte
     */
    public short retByte(short inByte)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetByte_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByte _myRetByte = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByte();
            _myRetByte.setInByte(inByte);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetByte_RetByte_QNAME);
            _bodyBlock.setValue(_myRetByte);
            _bodyBlock.setSerializer(ns1_myRetByte_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetByte");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse)_responseObj;
            }
            
            return _result.getRetByteResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retInt
     */
    public java.lang.Integer retInt(java.lang.Integer inInt)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetInt_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetInt _myRetInt = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetInt();
            _myRetInt.setInInt(inInt);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetInt_RetInt_QNAME);
            _bodyBlock.setValue(_myRetInt);
            _bodyBlock.setSerializer(ns1_myRetInt_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetInt");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse)_responseObj;
            }
            
            return _result.getRetIntResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retQName
     */
    public javax.xml.namespace.QName retQName(javax.xml.namespace.QName inQName)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetQName_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQName _myRetQName = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQName();
            _myRetQName.setInQName(inQName);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetQName_RetQName_QNAME);
            _bodyBlock.setValue(_myRetQName);
            _bodyBlock.setSerializer(ns1_myRetQName_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetQName");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse)_responseObj;
            }
            
            return _result.getRetQNameResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retLong
     */
    public java.lang.Long retLong(java.lang.Long inLong)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetLong_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLong _myRetLong = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLong();
            _myRetLong.setInLong(inLong);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetLong_RetLong_QNAME);
            _bodyBlock.setValue(_myRetLong);
            _bodyBlock.setSerializer(ns1_myRetLong_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetLong");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse)_responseObj;
            }
            
            return _result.getRetLongResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retSingle
     */
    public java.lang.Float retSingle(java.lang.Float inSingle)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetSingle_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingle _myRetSingle = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingle();
            _myRetSingle.setInSingle(inSingle);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetSingle_RetSingle_QNAME);
            _bodyBlock.setValue(_myRetSingle);
            _bodyBlock.setSerializer(ns1_myRetSingle_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetSingle");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse)_responseObj;
            }
            
            return _result.getRetSingleResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retUInt
     */
    public long retUInt(long inUInt)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetUInt_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUInt _myRetUInt = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUInt();
            _myRetUInt.setInUInt(inUInt);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetUInt_RetUInt_QNAME);
            _bodyBlock.setValue(_myRetUInt);
            _bodyBlock.setSerializer(ns1_myRetUInt_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IBaseDataTypesDocLitW/RetUInt");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse)_responseObj;
            }
            
            return _result.getRetUIntResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case RetDateTime_OPCODE:
                _deserialize_RetDateTime(bodyReader, deserializationContext, state);
                break;
            case RetSByte_OPCODE:
                _deserialize_RetSByte(bodyReader, deserializationContext, state);
                break;
            case RetFloat_OPCODE:
                _deserialize_RetFloat(bodyReader, deserializationContext, state);
                break;
            case RetBool_OPCODE:
                _deserialize_RetBool(bodyReader, deserializationContext, state);
                break;
            case RetShort_OPCODE:
                _deserialize_RetShort(bodyReader, deserializationContext, state);
                break;
            case RetDecimal_OPCODE:
                _deserialize_RetDecimal(bodyReader, deserializationContext, state);
                break;
            case RetUShort_OPCODE:
                _deserialize_RetUShort(bodyReader, deserializationContext, state);
                break;
            case RetByteArray_OPCODE:
                _deserialize_RetByteArray(bodyReader, deserializationContext, state);
                break;
            case RetString_OPCODE:
                _deserialize_RetString(bodyReader, deserializationContext, state);
                break;
            case RetDouble_OPCODE:
                _deserialize_RetDouble(bodyReader, deserializationContext, state);
                break;
            case RetULong_OPCODE:
                _deserialize_RetULong(bodyReader, deserializationContext, state);
                break;
            case RetTimeSpan_OPCODE:
                _deserialize_RetTimeSpan(bodyReader, deserializationContext, state);
                break;
            case RetUri_OPCODE:
                _deserialize_RetUri(bodyReader, deserializationContext, state);
                break;
            case RetChar_OPCODE:
                _deserialize_RetChar(bodyReader, deserializationContext, state);
                break;
            case RetGuid_OPCODE:
                _deserialize_RetGuid(bodyReader, deserializationContext, state);
                break;
            case RetObject_OPCODE:
                _deserialize_RetObject(bodyReader, deserializationContext, state);
                break;
            case RetByte_OPCODE:
                _deserialize_RetByte(bodyReader, deserializationContext, state);
                break;
            case RetInt_OPCODE:
                _deserialize_RetInt(bodyReader, deserializationContext, state);
                break;
            case RetQName_OPCODE:
                _deserialize_RetQName(bodyReader, deserializationContext, state);
                break;
            case RetLong_OPCODE:
                _deserialize_RetLong(bodyReader, deserializationContext, state);
                break;
            case RetSingle_OPCODE:
                _deserialize_RetSingle(bodyReader, deserializationContext, state);
                break;
            case RetUInt_OPCODE:
                _deserialize_RetUInt(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the RetDateTime operation.
     */
    private void _deserialize_RetDateTime(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetDateTimeResponseObj =
            ns1_myRetDateTimeResponse_LiteralSerializer.deserialize(ns1_RetDateTime_RetDateTimeResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetDateTime_RetDateTimeResponse_QNAME);
        bodyBlock.setValue(myRetDateTimeResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetSByte operation.
     */
    private void _deserialize_RetSByte(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetSByteResponseObj =
            ns1_myRetSByteResponse_LiteralSerializer.deserialize(ns1_RetSByte_RetSByteResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetSByte_RetSByteResponse_QNAME);
        bodyBlock.setValue(myRetSByteResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetFloat operation.
     */
    private void _deserialize_RetFloat(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetFloatResponseObj =
            ns1_myRetFloatResponse_LiteralSerializer.deserialize(ns1_RetFloat_RetFloatResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetFloat_RetFloatResponse_QNAME);
        bodyBlock.setValue(myRetFloatResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetBool operation.
     */
    private void _deserialize_RetBool(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetBoolResponseObj =
            ns1_myRetBoolResponse_LiteralSerializer.deserialize(ns1_RetBool_RetBoolResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetBool_RetBoolResponse_QNAME);
        bodyBlock.setValue(myRetBoolResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetShort operation.
     */
    private void _deserialize_RetShort(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetShortResponseObj =
            ns1_myRetShortResponse_LiteralSerializer.deserialize(ns1_RetShort_RetShortResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetShort_RetShortResponse_QNAME);
        bodyBlock.setValue(myRetShortResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetDecimal operation.
     */
    private void _deserialize_RetDecimal(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetDecimalResponseObj =
            ns1_myRetDecimalResponse_LiteralSerializer.deserialize(ns1_RetDecimal_RetDecimalResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetDecimal_RetDecimalResponse_QNAME);
        bodyBlock.setValue(myRetDecimalResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetUShort operation.
     */
    private void _deserialize_RetUShort(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetUShortResponseObj =
            ns1_myRetUShortResponse_LiteralSerializer.deserialize(ns1_RetUShort_RetUShortResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetUShort_RetUShortResponse_QNAME);
        bodyBlock.setValue(myRetUShortResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetByteArray operation.
     */
    private void _deserialize_RetByteArray(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetByteArrayResponseObj =
            ns1_myRetByteArrayResponse_LiteralSerializer.deserialize(ns1_RetByteArray_RetByteArrayResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetByteArray_RetByteArrayResponse_QNAME);
        bodyBlock.setValue(myRetByteArrayResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetString operation.
     */
    private void _deserialize_RetString(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetStringResponseObj =
            ns1_myRetStringResponse_LiteralSerializer.deserialize(ns1_RetString_RetStringResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetString_RetStringResponse_QNAME);
        bodyBlock.setValue(myRetStringResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetDouble operation.
     */
    private void _deserialize_RetDouble(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetDoubleResponseObj =
            ns1_myRetDoubleResponse_LiteralSerializer.deserialize(ns1_RetDouble_RetDoubleResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetDouble_RetDoubleResponse_QNAME);
        bodyBlock.setValue(myRetDoubleResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetULong operation.
     */
    private void _deserialize_RetULong(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetULongResponseObj =
            ns1_myRetULongResponse_LiteralSerializer.deserialize(ns1_RetULong_RetULongResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetULong_RetULongResponse_QNAME);
        bodyBlock.setValue(myRetULongResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetTimeSpan operation.
     */
    private void _deserialize_RetTimeSpan(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetTimeSpanResponseObj =
            ns1_myRetTimeSpanResponse_LiteralSerializer.deserialize(ns1_RetTimeSpan_RetTimeSpanResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetTimeSpan_RetTimeSpanResponse_QNAME);
        bodyBlock.setValue(myRetTimeSpanResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetUri operation.
     */
    private void _deserialize_RetUri(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetUriResponseObj =
            ns1_myRetUriResponse_LiteralSerializer.deserialize(ns1_RetUri_RetUriResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetUri_RetUriResponse_QNAME);
        bodyBlock.setValue(myRetUriResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetChar operation.
     */
    private void _deserialize_RetChar(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetCharResponseObj =
            ns1_myRetCharResponse_LiteralSerializer.deserialize(ns1_RetChar_RetCharResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetChar_RetCharResponse_QNAME);
        bodyBlock.setValue(myRetCharResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetGuid operation.
     */
    private void _deserialize_RetGuid(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetGuidResponseObj =
            ns1_myRetGuidResponse_LiteralSerializer.deserialize(ns1_RetGuid_RetGuidResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetGuid_RetGuidResponse_QNAME);
        bodyBlock.setValue(myRetGuidResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetObject operation.
     */
    private void _deserialize_RetObject(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetObjectResponseObj =
            ns1_myRetObjectResponse_LiteralSerializer.deserialize(ns1_RetObject_RetObjectResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetObject_RetObjectResponse_QNAME);
        bodyBlock.setValue(myRetObjectResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetByte operation.
     */
    private void _deserialize_RetByte(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetByteResponseObj =
            ns1_myRetByteResponse_LiteralSerializer.deserialize(ns1_RetByte_RetByteResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetByte_RetByteResponse_QNAME);
        bodyBlock.setValue(myRetByteResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetInt operation.
     */
    private void _deserialize_RetInt(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetIntResponseObj =
            ns1_myRetIntResponse_LiteralSerializer.deserialize(ns1_RetInt_RetIntResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetInt_RetIntResponse_QNAME);
        bodyBlock.setValue(myRetIntResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetQName operation.
     */
    private void _deserialize_RetQName(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetQNameResponseObj =
            ns1_myRetQNameResponse_LiteralSerializer.deserialize(ns1_RetQName_RetQNameResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetQName_RetQNameResponse_QNAME);
        bodyBlock.setValue(myRetQNameResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetLong operation.
     */
    private void _deserialize_RetLong(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetLongResponseObj =
            ns1_myRetLongResponse_LiteralSerializer.deserialize(ns1_RetLong_RetLongResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetLong_RetLongResponse_QNAME);
        bodyBlock.setValue(myRetLongResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetSingle operation.
     */
    private void _deserialize_RetSingle(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetSingleResponseObj =
            ns1_myRetSingleResponse_LiteralSerializer.deserialize(ns1_RetSingle_RetSingleResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetSingle_RetSingleResponse_QNAME);
        bodyBlock.setValue(myRetSingleResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetUInt operation.
     */
    private void _deserialize_RetUInt(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetUIntResponseObj =
            ns1_myRetUIntResponse_LiteralSerializer.deserialize(ns1_RetUInt_RetUIntResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetUInt_RetUIntResponse_QNAME);
        bodyBlock.setValue(myRetUIntResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    protected java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myRetQName_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQName.class, ns1_RetQName_TYPE_QNAME);
        ns1_myRetTimeSpan_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpan.class, ns1_RetTimeSpan_TYPE_QNAME);
        ns1_myRetUInt_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUInt.class, ns1_RetUInt_TYPE_QNAME);
        ns1_myRetBoolResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBoolResponse.class, ns1_RetBoolResponse_TYPE_QNAME);
        ns1_myRetDecimalResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimalResponse.class, ns1_RetDecimalResponse_TYPE_QNAME);
        ns1_myRetIntResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetIntResponse.class, ns1_RetIntResponse_TYPE_QNAME);
        ns1_myRetByte_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByte.class, ns1_RetByte_TYPE_QNAME);
        ns1_myRetShortResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShortResponse.class, ns1_RetShortResponse_TYPE_QNAME);
        ns1_myRetInt_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetInt.class, ns1_RetInt_TYPE_QNAME);
        ns1_myRetShort_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetShort.class, ns1_RetShort_TYPE_QNAME);
        ns1_myRetULong_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULong.class, ns1_RetULong_TYPE_QNAME);
        ns1_myRetUShort_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShort.class, ns1_RetUShort_TYPE_QNAME);
        ns1_myRetByteArray_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArray.class, ns1_RetByteArray_TYPE_QNAME);
        ns1_myRetDouble_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDouble.class, ns1_RetDouble_TYPE_QNAME);
        ns1_myRetStringResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetStringResponse.class, ns1_RetStringResponse_TYPE_QNAME);
        ns1_myRetByteResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteResponse.class, ns1_RetByteResponse_TYPE_QNAME);
        ns1_myRetUShortResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUShortResponse.class, ns1_RetUShortResponse_TYPE_QNAME);
        ns1_myRetUIntResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUIntResponse.class, ns1_RetUIntResponse_TYPE_QNAME);
        ns1_myRetDecimal_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDecimal.class, ns1_RetDecimal_TYPE_QNAME);
        ns1_myRetString_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetString.class, ns1_RetString_TYPE_QNAME);
        ns1_myRetULongResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetULongResponse.class, ns1_RetULongResponse_TYPE_QNAME);
        ns1_myRetSByteResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByteResponse.class, ns1_RetSByteResponse_TYPE_QNAME);
        ns1_myRetFloatResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloatResponse.class, ns1_RetFloatResponse_TYPE_QNAME);
        ns1_myRetUriResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUriResponse.class, ns1_RetUriResponse_TYPE_QNAME);
        ns1_myRetDoubleResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDoubleResponse.class, ns1_RetDoubleResponse_TYPE_QNAME);
        ns1_myRetSingle_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingle.class, ns1_RetSingle_TYPE_QNAME);
        ns1_myRetBool_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetBool.class, ns1_RetBool_TYPE_QNAME);
        ns1_myRetSingleResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSingleResponse.class, ns1_RetSingleResponse_TYPE_QNAME);
        ns1_myRetLongResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLongResponse.class, ns1_RetLongResponse_TYPE_QNAME);
        ns1_myRetTimeSpanResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetTimeSpanResponse.class, ns1_RetTimeSpanResponse_TYPE_QNAME);
        ns1_myRetSByte_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetSByte.class, ns1_RetSByte_TYPE_QNAME);
        ns1_myRetGuidResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuidResponse.class, ns1_RetGuidResponse_TYPE_QNAME);
        ns1_myRetCharResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetCharResponse.class, ns1_RetCharResponse_TYPE_QNAME);
        ns1_myRetChar_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetChar.class, ns1_RetChar_TYPE_QNAME);
        ns1_myRetQNameResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetQNameResponse.class, ns1_RetQNameResponse_TYPE_QNAME);
        ns1_myRetByteArrayResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetByteArrayResponse.class, ns1_RetByteArrayResponse_TYPE_QNAME);
        ns1_myRetDateTimeResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTimeResponse.class, ns1_RetDateTimeResponse_TYPE_QNAME);
        ns1_myRetUri_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetUri.class, ns1_RetUri_TYPE_QNAME);
        ns1_myRetFloat_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetFloat.class, ns1_RetFloat_TYPE_QNAME);
        ns1_myRetObject_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObject.class, ns1_RetObject_TYPE_QNAME);
        ns1_myRetDateTime_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetDateTime.class, ns1_RetDateTime_TYPE_QNAME);
        ns1_myRetGuid_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetGuid.class, ns1_RetGuid_TYPE_QNAME);
        ns1_myRetLong_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetLong.class, ns1_RetLong_TYPE_QNAME);
        ns1_myRetObjectResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.RetObjectResponse.class, ns1_RetObjectResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://tempuri.org/", "BasicHttpBinding_IBaseDataTypesDocLitW");
    private static final int RetDateTime_OPCODE = 0;
    private static final int RetSByte_OPCODE = 1;
    private static final int RetFloat_OPCODE = 2;
    private static final int RetBool_OPCODE = 3;
    private static final int RetShort_OPCODE = 4;
    private static final int RetDecimal_OPCODE = 5;
    private static final int RetUShort_OPCODE = 6;
    private static final int RetByteArray_OPCODE = 7;
    private static final int RetString_OPCODE = 8;
    private static final int RetDouble_OPCODE = 9;
    private static final int RetULong_OPCODE = 10;
    private static final int RetTimeSpan_OPCODE = 11;
    private static final int RetUri_OPCODE = 12;
    private static final int RetChar_OPCODE = 13;
    private static final int RetGuid_OPCODE = 14;
    private static final int RetObject_OPCODE = 15;
    private static final int RetByte_OPCODE = 16;
    private static final int RetInt_OPCODE = 17;
    private static final int RetQName_OPCODE = 18;
    private static final int RetLong_OPCODE = 19;
    private static final int RetSingle_OPCODE = 20;
    private static final int RetUInt_OPCODE = 21;
    private static final javax.xml.namespace.QName ns1_RetDateTime_RetDateTime_QNAME = new QName("http://tempuri.org/", "RetDateTime");
    private static final javax.xml.namespace.QName ns1_RetDateTime_TYPE_QNAME = new QName("http://tempuri.org/", "RetDateTime");
    private CombinedSerializer ns1_myRetDateTime_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDateTime_RetDateTimeResponse_QNAME = new QName("http://tempuri.org/", "RetDateTimeResponse");
    private static final javax.xml.namespace.QName ns1_RetDateTimeResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetDateTimeResponse");
    private CombinedSerializer ns1_myRetDateTimeResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetSByte_RetSByte_QNAME = new QName("http://tempuri.org/", "RetSByte");
    private static final javax.xml.namespace.QName ns1_RetSByte_TYPE_QNAME = new QName("http://tempuri.org/", "RetSByte");
    private CombinedSerializer ns1_myRetSByte_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetSByte_RetSByteResponse_QNAME = new QName("http://tempuri.org/", "RetSByteResponse");
    private static final javax.xml.namespace.QName ns1_RetSByteResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetSByteResponse");
    private CombinedSerializer ns1_myRetSByteResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetFloat_RetFloat_QNAME = new QName("http://tempuri.org/", "RetFloat");
    private static final javax.xml.namespace.QName ns1_RetFloat_TYPE_QNAME = new QName("http://tempuri.org/", "RetFloat");
    private CombinedSerializer ns1_myRetFloat_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetFloat_RetFloatResponse_QNAME = new QName("http://tempuri.org/", "RetFloatResponse");
    private static final javax.xml.namespace.QName ns1_RetFloatResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetFloatResponse");
    private CombinedSerializer ns1_myRetFloatResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetBool_RetBool_QNAME = new QName("http://tempuri.org/", "RetBool");
    private static final javax.xml.namespace.QName ns1_RetBool_TYPE_QNAME = new QName("http://tempuri.org/", "RetBool");
    private CombinedSerializer ns1_myRetBool_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetBool_RetBoolResponse_QNAME = new QName("http://tempuri.org/", "RetBoolResponse");
    private static final javax.xml.namespace.QName ns1_RetBoolResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetBoolResponse");
    private CombinedSerializer ns1_myRetBoolResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetShort_RetShort_QNAME = new QName("http://tempuri.org/", "RetShort");
    private static final javax.xml.namespace.QName ns1_RetShort_TYPE_QNAME = new QName("http://tempuri.org/", "RetShort");
    private CombinedSerializer ns1_myRetShort_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetShort_RetShortResponse_QNAME = new QName("http://tempuri.org/", "RetShortResponse");
    private static final javax.xml.namespace.QName ns1_RetShortResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetShortResponse");
    private CombinedSerializer ns1_myRetShortResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDecimal_RetDecimal_QNAME = new QName("http://tempuri.org/", "RetDecimal");
    private static final javax.xml.namespace.QName ns1_RetDecimal_TYPE_QNAME = new QName("http://tempuri.org/", "RetDecimal");
    private CombinedSerializer ns1_myRetDecimal_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDecimal_RetDecimalResponse_QNAME = new QName("http://tempuri.org/", "RetDecimalResponse");
    private static final javax.xml.namespace.QName ns1_RetDecimalResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetDecimalResponse");
    private CombinedSerializer ns1_myRetDecimalResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUShort_RetUShort_QNAME = new QName("http://tempuri.org/", "RetUShort");
    private static final javax.xml.namespace.QName ns1_RetUShort_TYPE_QNAME = new QName("http://tempuri.org/", "RetUShort");
    private CombinedSerializer ns1_myRetUShort_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUShort_RetUShortResponse_QNAME = new QName("http://tempuri.org/", "RetUShortResponse");
    private static final javax.xml.namespace.QName ns1_RetUShortResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetUShortResponse");
    private CombinedSerializer ns1_myRetUShortResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetByteArray_RetByteArray_QNAME = new QName("http://tempuri.org/", "RetByteArray");
    private static final javax.xml.namespace.QName ns1_RetByteArray_TYPE_QNAME = new QName("http://tempuri.org/", "RetByteArray");
    private CombinedSerializer ns1_myRetByteArray_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetByteArray_RetByteArrayResponse_QNAME = new QName("http://tempuri.org/", "RetByteArrayResponse");
    private static final javax.xml.namespace.QName ns1_RetByteArrayResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetByteArrayResponse");
    private CombinedSerializer ns1_myRetByteArrayResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetString_RetString_QNAME = new QName("http://tempuri.org/", "RetString");
    private static final javax.xml.namespace.QName ns1_RetString_TYPE_QNAME = new QName("http://tempuri.org/", "RetString");
    private CombinedSerializer ns1_myRetString_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetString_RetStringResponse_QNAME = new QName("http://tempuri.org/", "RetStringResponse");
    private static final javax.xml.namespace.QName ns1_RetStringResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetStringResponse");
    private CombinedSerializer ns1_myRetStringResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDouble_RetDouble_QNAME = new QName("http://tempuri.org/", "RetDouble");
    private static final javax.xml.namespace.QName ns1_RetDouble_TYPE_QNAME = new QName("http://tempuri.org/", "RetDouble");
    private CombinedSerializer ns1_myRetDouble_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDouble_RetDoubleResponse_QNAME = new QName("http://tempuri.org/", "RetDoubleResponse");
    private static final javax.xml.namespace.QName ns1_RetDoubleResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetDoubleResponse");
    private CombinedSerializer ns1_myRetDoubleResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetULong_RetULong_QNAME = new QName("http://tempuri.org/", "RetULong");
    private static final javax.xml.namespace.QName ns1_RetULong_TYPE_QNAME = new QName("http://tempuri.org/", "RetULong");
    private CombinedSerializer ns1_myRetULong_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetULong_RetULongResponse_QNAME = new QName("http://tempuri.org/", "RetULongResponse");
    private static final javax.xml.namespace.QName ns1_RetULongResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetULongResponse");
    private CombinedSerializer ns1_myRetULongResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetTimeSpan_RetTimeSpan_QNAME = new QName("http://tempuri.org/", "RetTimeSpan");
    private static final javax.xml.namespace.QName ns1_RetTimeSpan_TYPE_QNAME = new QName("http://tempuri.org/", "RetTimeSpan");
    private CombinedSerializer ns1_myRetTimeSpan_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetTimeSpan_RetTimeSpanResponse_QNAME = new QName("http://tempuri.org/", "RetTimeSpanResponse");
    private static final javax.xml.namespace.QName ns1_RetTimeSpanResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetTimeSpanResponse");
    private CombinedSerializer ns1_myRetTimeSpanResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUri_RetUri_QNAME = new QName("http://tempuri.org/", "RetUri");
    private static final javax.xml.namespace.QName ns1_RetUri_TYPE_QNAME = new QName("http://tempuri.org/", "RetUri");
    private CombinedSerializer ns1_myRetUri_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUri_RetUriResponse_QNAME = new QName("http://tempuri.org/", "RetUriResponse");
    private static final javax.xml.namespace.QName ns1_RetUriResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetUriResponse");
    private CombinedSerializer ns1_myRetUriResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetChar_RetChar_QNAME = new QName("http://tempuri.org/", "RetChar");
    private static final javax.xml.namespace.QName ns1_RetChar_TYPE_QNAME = new QName("http://tempuri.org/", "RetChar");
    private CombinedSerializer ns1_myRetChar_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetChar_RetCharResponse_QNAME = new QName("http://tempuri.org/", "RetCharResponse");
    private static final javax.xml.namespace.QName ns1_RetCharResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetCharResponse");
    private CombinedSerializer ns1_myRetCharResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetGuid_RetGuid_QNAME = new QName("http://tempuri.org/", "RetGuid");
    private static final javax.xml.namespace.QName ns1_RetGuid_TYPE_QNAME = new QName("http://tempuri.org/", "RetGuid");
    private CombinedSerializer ns1_myRetGuid_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetGuid_RetGuidResponse_QNAME = new QName("http://tempuri.org/", "RetGuidResponse");
    private static final javax.xml.namespace.QName ns1_RetGuidResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetGuidResponse");
    private CombinedSerializer ns1_myRetGuidResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetObject_RetObject_QNAME = new QName("http://tempuri.org/", "RetObject");
    private static final javax.xml.namespace.QName ns1_RetObject_TYPE_QNAME = new QName("http://tempuri.org/", "RetObject");
    private CombinedSerializer ns1_myRetObject_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetObject_RetObjectResponse_QNAME = new QName("http://tempuri.org/", "RetObjectResponse");
    private static final javax.xml.namespace.QName ns1_RetObjectResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetObjectResponse");
    private CombinedSerializer ns1_myRetObjectResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetByte_RetByte_QNAME = new QName("http://tempuri.org/", "RetByte");
    private static final javax.xml.namespace.QName ns1_RetByte_TYPE_QNAME = new QName("http://tempuri.org/", "RetByte");
    private CombinedSerializer ns1_myRetByte_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetByte_RetByteResponse_QNAME = new QName("http://tempuri.org/", "RetByteResponse");
    private static final javax.xml.namespace.QName ns1_RetByteResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetByteResponse");
    private CombinedSerializer ns1_myRetByteResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetInt_RetInt_QNAME = new QName("http://tempuri.org/", "RetInt");
    private static final javax.xml.namespace.QName ns1_RetInt_TYPE_QNAME = new QName("http://tempuri.org/", "RetInt");
    private CombinedSerializer ns1_myRetInt_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetInt_RetIntResponse_QNAME = new QName("http://tempuri.org/", "RetIntResponse");
    private static final javax.xml.namespace.QName ns1_RetIntResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetIntResponse");
    private CombinedSerializer ns1_myRetIntResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetQName_RetQName_QNAME = new QName("http://tempuri.org/", "RetQName");
    private static final javax.xml.namespace.QName ns1_RetQName_TYPE_QNAME = new QName("http://tempuri.org/", "RetQName");
    private CombinedSerializer ns1_myRetQName_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetQName_RetQNameResponse_QNAME = new QName("http://tempuri.org/", "RetQNameResponse");
    private static final javax.xml.namespace.QName ns1_RetQNameResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetQNameResponse");
    private CombinedSerializer ns1_myRetQNameResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetLong_RetLong_QNAME = new QName("http://tempuri.org/", "RetLong");
    private static final javax.xml.namespace.QName ns1_RetLong_TYPE_QNAME = new QName("http://tempuri.org/", "RetLong");
    private CombinedSerializer ns1_myRetLong_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetLong_RetLongResponse_QNAME = new QName("http://tempuri.org/", "RetLongResponse");
    private static final javax.xml.namespace.QName ns1_RetLongResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetLongResponse");
    private CombinedSerializer ns1_myRetLongResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetSingle_RetSingle_QNAME = new QName("http://tempuri.org/", "RetSingle");
    private static final javax.xml.namespace.QName ns1_RetSingle_TYPE_QNAME = new QName("http://tempuri.org/", "RetSingle");
    private CombinedSerializer ns1_myRetSingle_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetSingle_RetSingleResponse_QNAME = new QName("http://tempuri.org/", "RetSingleResponse");
    private static final javax.xml.namespace.QName ns1_RetSingleResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetSingleResponse");
    private CombinedSerializer ns1_myRetSingleResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUInt_RetUInt_QNAME = new QName("http://tempuri.org/", "RetUInt");
    private static final javax.xml.namespace.QName ns1_RetUInt_TYPE_QNAME = new QName("http://tempuri.org/", "RetUInt");
    private CombinedSerializer ns1_myRetUInt_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetUInt_RetUIntResponse_QNAME = new QName("http://tempuri.org/", "RetUIntResponse");
    private static final javax.xml.namespace.QName ns1_RetUIntResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetUIntResponse");
    private CombinedSerializer ns1_myRetUIntResponse_LiteralSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://tempuri.org/"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
