<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="http://xmlsoap.org/Ping" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlsoap.org/Ping" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:ci="http://schemas.microsoft.com/ws/2005/01/WSDL/Extensions/ContractInheritance" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://xmlsoap.org/Ping/Imports">
            <xsd:import schemaLocation="WSSecurity_schema.xsd" namespace="http://xmlsoap.org/Ping"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="PingRequest">
        <wsdl:part name="Ping" element="tns:Ping"/>
    </wsdl:message>
    <wsdl:message name="PingResponse">
        <wsdl:part name="PingResponse" element="tns:PingResponse"/>
    </wsdl:message>
    <wsdl:portType name="IPingService">
        <wsdl:operation name="Ping">
            <wsdl:input wsa:Action="http://xmlsoap.org/Ping" name="PingRequest" message="tns:PingRequest"/>
            <wsdl:output wsa:Action="http://xmlsoap.org/PingResponse" name="PingResponse" message="tns:PingResponse"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>