
package org.jboss.test.ws.jaxws.jbws2930;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PhoneBook", targetNamespace = "http://test.jboss.org/ws/jbws2930", wsdlLocation = "file:/home/darranl/src/jbossws/jbossws-native/modules/testsuite/native-tests/src/test/resources/jaxws/jbws2930/WEB-INF/wsdl/PhoneBook.wsdl")
public class PhoneBook_Service
    extends Service
{

    private final static URL PHONEBOOK_WSDL_LOCATION;
    private final static WebServiceException PHONEBOOK_EXCEPTION;
    private final static QName PHONEBOOK_QNAME = new QName("http://test.jboss.org/ws/jbws2930", "PhoneBook");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/darranl/src/jbossws/jbossws-native/modules/testsuite/native-tests/src/test/resources/jaxws/jbws2930/WEB-INF/wsdl/PhoneBook.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONEBOOK_WSDL_LOCATION = url;
        PHONEBOOK_EXCEPTION = e;
    }

    public PhoneBook_Service() {
        super(__getWsdlLocation(), PHONEBOOK_QNAME);
    }

    public PhoneBook_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PhoneBook
     */
    @WebEndpoint(name = "PhoneBookPort")
    public PhoneBook getPhoneBookPort() {
        return super.getPort(new QName("http://test.jboss.org/ws/jbws2930", "PhoneBookPort"), PhoneBook.class);
    }

    private static URL __getWsdlLocation() {
        if (PHONEBOOK_EXCEPTION!= null) {
            throw PHONEBOOK_EXCEPTION;
        }
        return PHONEBOOK_WSDL_LOCATION;
    }

}
