
package org.jboss.test.ws.interop.nov2007.wsse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPingService", targetNamespace = "http://xmlsoap.org/Ping")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IPingService {


    /**
     * 
     * @param ping
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "http://xmlsoap.org/Ping")
    @WebResult(name = "PingResponse", targetNamespace = "http://xmlsoap.org/Ping", partName = "PingResponse")
    @Action(input = "http://xmlsoap.org/Ping", output = "http://xmlsoap.org/PingResponse")
    public String ping(
        @WebParam(name = "Ping", targetNamespace = "http://xmlsoap.org/Ping", partName = "Ping")
        String ping);

}
