// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Furniture_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_Table_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Table");
    private CombinedSerializer ns1_myTable_LiteralSerializer;
    private CombinedSerializer ns1_myFurniture_LiteralSerializer;
    
    public Furniture_InterfaceSOAPSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, encodeType, true, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myTable_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table.class, ns1_Table_TYPE_QNAME);
        ns1_myTable_LiteralSerializer = ns1_myTable_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Furniture");
        CombinedSerializer interfaceSerializer = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Furniture_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
        ns1_myFurniture_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (ns1_myFurniture_LiteralSerializer instanceof Initializable) {
            ((Initializable)ns1_myFurniture_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(javax.xml.namespace.QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        javax.xml.namespace.QName elementType = getType(reader);
        if (elementType != null && elementType.equals(ns1_myTable_LiteralSerializer.getXmlType())) {
            return ns1_myTable_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(ns1_myFurniture_LiteralSerializer.getXmlType())) {
            Object obj = ns1_myFurniture_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new Object[] {"", elementType.toString()});
    }
    
    public void doSerializeInstance(java.lang.Object obj, javax.xml.namespace.QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Furniture instance = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Furniture)obj;
        
        if (obj instanceof org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table) {
            ns1_myTable_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            ns1_myFurniture_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
