// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class IComplexDataTypesDocLitB_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IComplexDataTypesDocLitB {
    
    
    
    /*
     *  public constructor
     */
    public IComplexDataTypesDocLitB_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://131.107.72.15/SoapWsdl_ComplexDataTypes_XmlFormatter_Service_Indigo/ComplexDataTypesDocLitB.svc");
    }
    
    
    /*
     *  implementation of retStructSNSAS
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group retStructSNSAS(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group inStructSNSAS)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSNSAS_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSAS_inStructSNSAS_QNAME);
            _bodyBlock.setValue(inStructSNSAS);
            _bodyBlock.setSerializer(ns2_myGroup_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetStructSNSAS");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayString2D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring retArrayString2D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring inArrayString2D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayString2D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayString2D_inArrayString2D_QNAME);
            _bodyBlock.setValue(inArrayString2D);
            _bodyBlock.setSerializer(ns3_myArrayOfArrayOfstring_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayString2D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayDecimal1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal retArrayDecimal1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal inArrayDecimal1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayDecimal1D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayDecimal1D_inArrayDecimal1D_QNAME);
            _bodyBlock.setValue(inArrayDecimal1D);
            _bodyBlock.setSerializer(ns4_myArrayOfNullableOfdecimal_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayDecimal1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retEnumString
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask retEnumString(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask inEnumString)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetEnumString_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetEnumString_inEnumString_QNAME);
            _bodyBlock.setValue(inEnumString);
            _bodyBlock.setSerializer(ns2myns2_BitMask__BitMask_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetEnumString");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayDateTime1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime retArrayDateTime1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime inArrayDateTime1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayDateTime1D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayDateTime1D_inArrayDateTime1D_QNAME);
            _bodyBlock.setValue(inArrayDateTime1D);
            _bodyBlock.setSerializer(ns4_myArrayOfNullableOfdateTime_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayDateTime1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayAnyType1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType retArrayAnyType1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType inArrayAnyType1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayAnyType1D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayAnyType1D_inArrayAnyType1D_QNAME);
            _bodyBlock.setValue(inArrayAnyType1D);
            _bodyBlock.setSerializer(ns3_myArrayOfanyType_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayAnyType1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArray1D_SN
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson retArray1D_SN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson inArray1D_SN)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArray1D_SN_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArray1D_SN_inArray1D_SN_QNAME);
            _bodyBlock.setValue(inArray1D_SN);
            _bodyBlock.setSerializer(ns2_myArrayOfPerson_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArray1D_SN");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructS1
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name retStructS1(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name inStructS1)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructS1_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructS1_inStructS1_QNAME);
            _bodyBlock.setValue(inStructS1);
            _bodyBlock.setSerializer(ns2_myName_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetStructS1");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayString1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring retArrayString1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring inArrayString1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayString1D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayString1D_inArrayString1D_QNAME);
            _bodyBlock.setValue(inArrayString1D);
            _bodyBlock.setSerializer(ns3_myArrayOfstring_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayString1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retEnumInt
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet retEnumInt(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet inEnumInt)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetEnumInt_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetEnumInt_inEnumInt_QNAME);
            _bodyBlock.setValue(inEnumInt);
            _bodyBlock.setSerializer(ns2myns2_IntSet__IntSet_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetEnumInt");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayInt1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint retArrayInt1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint inArrayInt1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayInt1D_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayInt1D_inArrayInt1D_QNAME);
            _bodyBlock.setValue(inArrayInt1D);
            _bodyBlock.setSerializer(ns3_myArrayOfint_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetArrayInt1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retDerivedClass
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table retDerivedClass(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table inDerivedClass)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetDerivedClass_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetDerivedClass_inDerivedClass_QNAME);
            _bodyBlock.setValue(inDerivedClass);
            _bodyBlock.setSerializer(ns2_myTable_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetDerivedClass");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructSN
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person retStructSN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person inStructSN)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSN_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSN_inStructSN_QNAME);
            _bodyBlock.setValue(inStructSN);
            _bodyBlock.setSerializer(ns2_myPerson_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetStructSN");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructSNSA
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee retStructSNSA(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSNSA_OPCODE);
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSA_inStructSNSA_QNAME);
            _bodyBlock.setValue(inStructSNSA);
            _bodyBlock.setSerializer(ns2_myEmployee_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitB/RetStructSNSA");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case RetStructSNSAS_OPCODE:
                _deserialize_RetStructSNSAS(bodyReader, deserializationContext, state);
                break;
            case RetArrayString2D_OPCODE:
                _deserialize_RetArrayString2D(bodyReader, deserializationContext, state);
                break;
            case RetArrayDecimal1D_OPCODE:
                _deserialize_RetArrayDecimal1D(bodyReader, deserializationContext, state);
                break;
            case RetEnumString_OPCODE:
                _deserialize_RetEnumString(bodyReader, deserializationContext, state);
                break;
            case RetArrayDateTime1D_OPCODE:
                _deserialize_RetArrayDateTime1D(bodyReader, deserializationContext, state);
                break;
            case RetArrayAnyType1D_OPCODE:
                _deserialize_RetArrayAnyType1D(bodyReader, deserializationContext, state);
                break;
            case RetArray1D_SN_OPCODE:
                _deserialize_RetArray1D_SN(bodyReader, deserializationContext, state);
                break;
            case RetStructS1_OPCODE:
                _deserialize_RetStructS1(bodyReader, deserializationContext, state);
                break;
            case RetArrayString1D_OPCODE:
                _deserialize_RetArrayString1D(bodyReader, deserializationContext, state);
                break;
            case RetEnumInt_OPCODE:
                _deserialize_RetEnumInt(bodyReader, deserializationContext, state);
                break;
            case RetArrayInt1D_OPCODE:
                _deserialize_RetArrayInt1D(bodyReader, deserializationContext, state);
                break;
            case RetDerivedClass_OPCODE:
                _deserialize_RetDerivedClass(bodyReader, deserializationContext, state);
                break;
            case RetStructSN_OPCODE:
                _deserialize_RetStructSN(bodyReader, deserializationContext, state);
                break;
            case RetStructSNSA_OPCODE:
                _deserialize_RetStructSNSA(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the RetStructSNSAS operation.
     */
    private void _deserialize_RetStructSNSAS(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myGroupObj =
            ns2_myGroup_LiteralSerializer.deserialize(ns1_RetStructSNSAS_RetStructSNSASResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSAS_RetStructSNSASResult_QNAME);
        bodyBlock.setValue(myGroupObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayString2D operation.
     */
    private void _deserialize_RetArrayString2D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfArrayOfstringObj =
            ns3_myArrayOfArrayOfstring_LiteralSerializer.deserialize(ns1_RetArrayString2D_RetArrayString2DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayString2D_RetArrayString2DResult_QNAME);
        bodyBlock.setValue(myArrayOfArrayOfstringObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayDecimal1D operation.
     */
    private void _deserialize_RetArrayDecimal1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfNullableOfdecimalObj =
            ns4_myArrayOfNullableOfdecimal_LiteralSerializer.deserialize(ns1_RetArrayDecimal1D_RetArrayDecimal1DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayDecimal1D_RetArrayDecimal1DResult_QNAME);
        bodyBlock.setValue(myArrayOfNullableOfdecimalObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetEnumString operation.
     */
    private void _deserialize_RetEnumString(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myBitMaskObj =
            ns2myns2_BitMask__BitMask_LiteralSerializer.deserialize(ns1_RetEnumString_RetEnumStringResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetEnumString_RetEnumStringResult_QNAME);
        bodyBlock.setValue(myBitMaskObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayDateTime1D operation.
     */
    private void _deserialize_RetArrayDateTime1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfNullableOfdateTimeObj =
            ns4_myArrayOfNullableOfdateTime_LiteralSerializer.deserialize(ns1_RetArrayDateTime1D_RetArrayDateTime1DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayDateTime1D_RetArrayDateTime1DResult_QNAME);
        bodyBlock.setValue(myArrayOfNullableOfdateTimeObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayAnyType1D operation.
     */
    private void _deserialize_RetArrayAnyType1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfanyTypeObj =
            ns3_myArrayOfanyType_LiteralSerializer.deserialize(ns1_RetArrayAnyType1D_RetArrayAnyType1DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayAnyType1D_RetArrayAnyType1DResult_QNAME);
        bodyBlock.setValue(myArrayOfanyTypeObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArray1D_SN operation.
     */
    private void _deserialize_RetArray1D_SN(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfPersonObj =
            ns2_myArrayOfPerson_LiteralSerializer.deserialize(ns1_RetArray1D_SN_RetArray1D_SNResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArray1D_SN_RetArray1D_SNResult_QNAME);
        bodyBlock.setValue(myArrayOfPersonObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructS1 operation.
     */
    private void _deserialize_RetStructS1(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myNameObj =
            ns2_myName_LiteralSerializer.deserialize(ns1_RetStructS1_RetStructS1Result_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructS1_RetStructS1Result_QNAME);
        bodyBlock.setValue(myNameObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayString1D operation.
     */
    private void _deserialize_RetArrayString1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfstringObj =
            ns3_myArrayOfstring_LiteralSerializer.deserialize(ns1_RetArrayString1D_RetArrayString1DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayString1D_RetArrayString1DResult_QNAME);
        bodyBlock.setValue(myArrayOfstringObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetEnumInt operation.
     */
    private void _deserialize_RetEnumInt(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myIntSetObj =
            ns2myns2_IntSet__IntSet_LiteralSerializer.deserialize(ns1_RetEnumInt_RetEnumIntResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetEnumInt_RetEnumIntResult_QNAME);
        bodyBlock.setValue(myIntSetObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayInt1D operation.
     */
    private void _deserialize_RetArrayInt1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myArrayOfintObj =
            ns3_myArrayOfint_LiteralSerializer.deserialize(ns1_RetArrayInt1D_RetArrayInt1DResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayInt1D_RetArrayInt1DResult_QNAME);
        bodyBlock.setValue(myArrayOfintObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetDerivedClass operation.
     */
    private void _deserialize_RetDerivedClass(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myTableObj =
            ns2_myTable_LiteralSerializer.deserialize(ns1_RetDerivedClass_RetDerivedClassResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetDerivedClass_RetDerivedClassResult_QNAME);
        bodyBlock.setValue(myTableObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructSN operation.
     */
    private void _deserialize_RetStructSN(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myPersonObj =
            ns2_myPerson_LiteralSerializer.deserialize(ns1_RetStructSN_RetStructSNResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSN_RetStructSNResult_QNAME);
        bodyBlock.setValue(myPersonObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructSNSA operation.
     */
    private void _deserialize_RetStructSNSA(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myEmployeeObj =
            ns2_myEmployee_LiteralSerializer.deserialize(ns1_RetStructSNSA_RetStructSNSAResult_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSA_RetStructSNSAResult_QNAME);
        bodyBlock.setValue(myEmployeeObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    protected java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns3_myArrayOfanyType_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType.class, ns3_ArrayOfanyType_TYPE_QNAME);
        ns2_myArrayOfPerson_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson.class, ns2_ArrayOfPerson_TYPE_QNAME);
        ns4_myArrayOfNullableOfdecimal_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal.class, ns4_ArrayOfNullableOfdecimal_TYPE_QNAME);
        ns3_myArrayOfint_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint.class, ns3_ArrayOfint_TYPE_QNAME);
        ns2_myPerson_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person.class, ns2_Person_TYPE_QNAME);
        ns2_myTable_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table.class, ns2_Table_TYPE_QNAME);
        ns3_myArrayOfArrayOfstring_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring.class, ns3_ArrayOfArrayOfstring_TYPE_QNAME);
        ns2_myName_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name.class, ns2_Name_TYPE_QNAME);
        ns2myns2_IntSet__IntSet_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet.class, ns2_IntSet_TYPE_QNAME);
        ns2_myGroup_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group.class, ns2_Group_TYPE_QNAME);
        ns2_myEmployee_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee.class, ns2_Employee_TYPE_QNAME);
        ns2myns2_BitMask__BitMask_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask.class, ns2_BitMask_TYPE_QNAME);
        ns3_myArrayOfstring_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring.class, ns3_ArrayOfstring_TYPE_QNAME);
        ns4_myArrayOfNullableOfdateTime_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime.class, ns4_ArrayOfNullableOfdateTime_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://tempuri.org/", "BasicHttpBinding_IComplexDataTypesDocLitB");
    private static final int RetStructSNSAS_OPCODE = 0;
    private static final int RetArrayString2D_OPCODE = 1;
    private static final int RetArrayDecimal1D_OPCODE = 2;
    private static final int RetEnumString_OPCODE = 3;
    private static final int RetArrayDateTime1D_OPCODE = 4;
    private static final int RetArrayAnyType1D_OPCODE = 5;
    private static final int RetArray1D_SN_OPCODE = 6;
    private static final int RetStructS1_OPCODE = 7;
    private static final int RetArrayString1D_OPCODE = 8;
    private static final int RetEnumInt_OPCODE = 9;
    private static final int RetArrayInt1D_OPCODE = 10;
    private static final int RetDerivedClass_OPCODE = 11;
    private static final int RetStructSN_OPCODE = 12;
    private static final int RetStructSNSA_OPCODE = 13;
    private static final javax.xml.namespace.QName ns1_RetStructSNSAS_inStructSNSAS_QNAME = new QName("http://tempuri.org/", "inStructSNSAS");
    private static final javax.xml.namespace.QName ns2_Group_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Group");
    private CombinedSerializer ns2_myGroup_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSAS_RetStructSNSASResult_QNAME = new QName("http://tempuri.org/", "RetStructSNSASResult");
    private static final javax.xml.namespace.QName ns1_RetArrayString2D_inArrayString2D_QNAME = new QName("http://tempuri.org/", "inArrayString2D");
    private static final javax.xml.namespace.QName ns3_ArrayOfArrayOfstring_TYPE_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfArrayOfstring");
    private CombinedSerializer ns3_myArrayOfArrayOfstring_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString2D_RetArrayString2DResult_QNAME = new QName("http://tempuri.org/", "RetArrayString2DResult");
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1D_inArrayDecimal1D_QNAME = new QName("http://tempuri.org/", "inArrayDecimal1D");
    private static final javax.xml.namespace.QName ns4_ArrayOfNullableOfdecimal_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/System", "ArrayOfNullableOfdecimal");
    private CombinedSerializer ns4_myArrayOfNullableOfdecimal_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1D_RetArrayDecimal1DResult_QNAME = new QName("http://tempuri.org/", "RetArrayDecimal1DResult");
    private static final javax.xml.namespace.QName ns1_RetEnumString_inEnumString_QNAME = new QName("http://tempuri.org/", "inEnumString");
    private static final javax.xml.namespace.QName ns2_BitMask_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "BitMask");
    private CombinedSerializer ns2myns2_BitMask__BitMask_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumString_RetEnumStringResult_QNAME = new QName("http://tempuri.org/", "RetEnumStringResult");
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1D_inArrayDateTime1D_QNAME = new QName("http://tempuri.org/", "inArrayDateTime1D");
    private static final javax.xml.namespace.QName ns4_ArrayOfNullableOfdateTime_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/System", "ArrayOfNullableOfdateTime");
    private CombinedSerializer ns4_myArrayOfNullableOfdateTime_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1D_RetArrayDateTime1DResult_QNAME = new QName("http://tempuri.org/", "RetArrayDateTime1DResult");
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1D_inArrayAnyType1D_QNAME = new QName("http://tempuri.org/", "inArrayAnyType1D");
    private static final javax.xml.namespace.QName ns3_ArrayOfanyType_TYPE_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfanyType");
    private CombinedSerializer ns3_myArrayOfanyType_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1D_RetArrayAnyType1DResult_QNAME = new QName("http://tempuri.org/", "RetArrayAnyType1DResult");
    private static final javax.xml.namespace.QName ns1_RetArray1D_SN_inArray1D_SN_QNAME = new QName("http://tempuri.org/", "inArray1D_SN");
    private static final javax.xml.namespace.QName ns2_ArrayOfPerson_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "ArrayOfPerson");
    private CombinedSerializer ns2_myArrayOfPerson_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArray1D_SN_RetArray1D_SNResult_QNAME = new QName("http://tempuri.org/", "RetArray1D_SNResult");
    private static final javax.xml.namespace.QName ns1_RetStructS1_inStructS1_QNAME = new QName("http://tempuri.org/", "inStructS1");
    private static final javax.xml.namespace.QName ns2_Name_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Name");
    private CombinedSerializer ns2_myName_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructS1_RetStructS1Result_QNAME = new QName("http://tempuri.org/", "RetStructS1Result");
    private static final javax.xml.namespace.QName ns1_RetArrayString1D_inArrayString1D_QNAME = new QName("http://tempuri.org/", "inArrayString1D");
    private static final javax.xml.namespace.QName ns3_ArrayOfstring_TYPE_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfstring");
    private CombinedSerializer ns3_myArrayOfstring_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString1D_RetArrayString1DResult_QNAME = new QName("http://tempuri.org/", "RetArrayString1DResult");
    private static final javax.xml.namespace.QName ns1_RetEnumInt_inEnumInt_QNAME = new QName("http://tempuri.org/", "inEnumInt");
    private static final javax.xml.namespace.QName ns2_IntSet_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "IntSet");
    private CombinedSerializer ns2myns2_IntSet__IntSet_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumInt_RetEnumIntResult_QNAME = new QName("http://tempuri.org/", "RetEnumIntResult");
    private static final javax.xml.namespace.QName ns1_RetArrayInt1D_inArrayInt1D_QNAME = new QName("http://tempuri.org/", "inArrayInt1D");
    private static final javax.xml.namespace.QName ns3_ArrayOfint_TYPE_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfint");
    private CombinedSerializer ns3_myArrayOfint_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayInt1D_RetArrayInt1DResult_QNAME = new QName("http://tempuri.org/", "RetArrayInt1DResult");
    private static final javax.xml.namespace.QName ns1_RetDerivedClass_inDerivedClass_QNAME = new QName("http://tempuri.org/", "inDerivedClass");
    private static final javax.xml.namespace.QName ns2_Table_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Table");
    private CombinedSerializer ns2_myTable_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDerivedClass_RetDerivedClassResult_QNAME = new QName("http://tempuri.org/", "RetDerivedClassResult");
    private static final javax.xml.namespace.QName ns1_RetStructSN_inStructSN_QNAME = new QName("http://tempuri.org/", "inStructSN");
    private static final javax.xml.namespace.QName ns2_Person_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Person");
    private CombinedSerializer ns2_myPerson_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSN_RetStructSNResult_QNAME = new QName("http://tempuri.org/", "RetStructSNResult");
    private static final javax.xml.namespace.QName ns1_RetStructSNSA_inStructSNSA_QNAME = new QName("http://tempuri.org/", "inStructSNSA");
    private static final javax.xml.namespace.QName ns2_Employee_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Employee");
    private CombinedSerializer ns2_myEmployee_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSA_RetStructSNSAResult_QNAME = new QName("http://tempuri.org/", "RetStructSNSAResult");
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo",
                                            "ns1", "http://schemas.microsoft.com/2003/10/Serialization/Arrays",
                                            "ns2", "http://schemas.datacontract.org/2004/07/System"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
