// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.addressing.wsa10;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class WSAddressingCR_Impl extends com.sun.xml.rpc.client.BasicService implements WSAddressingCR {
    private static final QName serviceName = new QName("http://tempuri.org/", "WSAddressingCR");
    private static final QName ns1_CustomBinding_Notify_QNAME = new QName("http://tempuri.org/", "CustomBinding_Notify");
    private static final Class notify_PortClass = org.jboss.test.ws.interop.microsoft.addressing.wsa10.Notify.class;
    private static final QName ns1_CustomBinding_Echo_QNAME = new QName("http://tempuri.org/", "CustomBinding_Echo");
    private static final Class echo_PortClass = org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo.class;
    private static final QName ns1_CustomBinding_Echo2_QNAME = new QName("http://tempuri.org/", "CustomBinding_Echo2");
    private static final Class echo2_PortClass = org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo2.class;
    private static final QName ns1_CustomBinding_Echo4_QNAME = new QName("http://tempuri.org/", "CustomBinding_Echo4");
    private static final Class echo4_PortClass = org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo4.class;
    
    public WSAddressingCR_Impl() {
        super(serviceName, new QName[] {
                        ns1_CustomBinding_Notify_QNAME,
                        ns1_CustomBinding_Echo_QNAME,
                        ns1_CustomBinding_Echo2_QNAME,
                        ns1_CustomBinding_Echo4_QNAME
                    },
            new org.jboss.test.ws.interop.microsoft.addressing.wsa10.WSAddressingCR_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_CustomBinding_Notify_QNAME) &&
                serviceDefInterface.equals(notify_PortClass)) {
                return getCustomBinding_Notify();
            }
            if (portName.equals(ns1_CustomBinding_Echo_QNAME) &&
                serviceDefInterface.equals(echo_PortClass)) {
                return getCustomBinding_Echo();
            }
            if (portName.equals(ns1_CustomBinding_Echo2_QNAME) &&
                serviceDefInterface.equals(echo2_PortClass)) {
                return getCustomBinding_Echo2();
            }
            if (portName.equals(ns1_CustomBinding_Echo4_QNAME) &&
                serviceDefInterface.equals(echo4_PortClass)) {
                return getCustomBinding_Echo4();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(notify_PortClass)) {
                return getCustomBinding_Notify();
            }
            if (serviceDefInterface.equals(echo_PortClass)) {
                return getCustomBinding_Echo();
            }
            if (serviceDefInterface.equals(echo2_PortClass)) {
                return getCustomBinding_Echo2();
            }
            if (serviceDefInterface.equals(echo4_PortClass)) {
                return getCustomBinding_Echo4();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Notify getCustomBinding_Notify() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_CustomBinding_Notify_QNAME));
        handlerChain.setRoles(roles);
        org.jboss.test.ws.interop.microsoft.addressing.wsa10.Notify_Stub stub = new org.jboss.test.ws.interop.microsoft.addressing.wsa10.Notify_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo getCustomBinding_Echo() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_CustomBinding_Echo_QNAME));
        handlerChain.setRoles(roles);
        org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo_Stub stub = new org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo2 getCustomBinding_Echo2() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_CustomBinding_Echo2_QNAME));
        handlerChain.setRoles(roles);
        org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo2_Stub stub = new org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo2_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo4 getCustomBinding_Echo4() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_CustomBinding_Echo4_QNAME));
        handlerChain.setRoles(roles);
        org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo4_Stub stub = new org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo4_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
