// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class Employee_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns5_BaseDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "BaseDetails");
    private static final javax.xml.namespace.QName ns5_Person_TYPE_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "Person");
    private CombinedSerializer ns5_myPerson_LiteralSerializer;
    private static final javax.xml.namespace.QName ns5_HireDate_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "HireDate");
    private static final javax.xml.namespace.QName ns2_dateTime_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DATE_TIME;
    private CombinedSerializer ns2_myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer;
    private static final javax.xml.namespace.QName ns5_JobID_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "JobID");
    private static final javax.xml.namespace.QName ns2_unsignedInt_TYPE_QNAME = SchemaConstants.QNAME_TYPE_UNSIGNED_INT;
    private CombinedSerializer ns2_myns2_unsignedInt__long_UnsignedInt_Serializer;
    private static final javax.xml.namespace.QName ns5_numbers_QNAME = new QName("http://schemas.datacontract.org/2004/07/XwsInterop.SoapWsdl.ComplexDataTypes.XmlFormatter.Service.Indigo", "numbers");
    private static final javax.xml.namespace.QName ns1_ArrayOfshort_TYPE_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfshort");
    private CombinedSerializer ns1_myArrayOfshort_LiteralSerializer;
    
    public Employee_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public Employee_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns5_myPerson_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person.class, ns5_Person_TYPE_QNAME);
        ns2_myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer = (CombinedSerializer)registry.getSerializer("", java.util.Calendar.class, ns2_dateTime_TYPE_QNAME);
        ns2_myns2_unsignedInt__long_UnsignedInt_Serializer = (CombinedSerializer)registry.getSerializer("", long.class, ns2_unsignedInt_TYPE_QNAME);
        ns1_myArrayOfshort_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort.class, ns1_ArrayOfshort_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee instance = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_BaseDetails_QNAME)) {
                member = ns5_myPerson_LiteralSerializer.deserialize(ns5_BaseDetails_QNAME, reader, context);
                instance.setBaseDetails((org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_HireDate_QNAME)) {
                member = ns2_myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.deserialize(ns5_HireDate_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setHireDate((java.util.Calendar)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_JobID_QNAME)) {
                member = ns2_myns2_unsignedInt__long_UnsignedInt_Serializer.deserialize(ns5_JobID_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setJobID(((Long)member).longValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_numbers_QNAME)) {
                member = ns1_myArrayOfshort_LiteralSerializer.deserialize(ns5_numbers_QNAME, reader, context);
                instance.setNumbers((org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee instance = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee instance = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee)obj;
        
        ns5_myPerson_LiteralSerializer.serialize(instance.getBaseDetails(), ns5_BaseDetails_QNAME, null, writer, context);
        if (instance.getHireDate() != null) {
            ns2_myns2_dateTime__java_util_Calendar_DateTimeCalendar_Serializer.serialize(instance.getHireDate(), ns5_HireDate_QNAME, null, writer, context);
        }
        ns2_myns2_unsignedInt__long_UnsignedInt_Serializer.serialize(new Long(instance.getJobID()), ns5_JobID_QNAME, null, writer, context);
        ns1_myArrayOfshort_LiteralSerializer.serialize(instance.getNumbers(), ns5_numbers_QNAME, null, writer, context);
    }
}
