// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class IComplexDataTypesDocLitW_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IComplexDataTypesDocLitW {
    
    
    
    /*
     *  public constructor
     */
    public IComplexDataTypesDocLitW_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://131.107.72.15/SoapWsdl_ComplexDataTypes_XmlFormatter_Service_Indigo/ComplexDataTypesDocLitW.svc");
    }
    
    
    /*
     *  implementation of retStructSN
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person retStructSN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person inStructSN)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSN_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSN _myRetStructSN = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSN();
            _myRetStructSN.setInStructSN(inStructSN);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSN_RetStructSN_QNAME);
            _bodyBlock.setValue(_myRetStructSN);
            _bodyBlock.setSerializer(ns1_myRetStructSN_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetStructSN");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNResponse)_responseObj;
            }
            
            return _result.getRetStructSNResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retDerivedClass
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table retDerivedClass(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table inDerivedClass)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetDerivedClass_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClass _myRetDerivedClass = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClass();
            _myRetDerivedClass.setInDerivedClass(inDerivedClass);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetDerivedClass_RetDerivedClass_QNAME);
            _bodyBlock.setValue(_myRetDerivedClass);
            _bodyBlock.setSerializer(ns1_myRetDerivedClass_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetDerivedClass");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClassResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClassResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClassResponse)_responseObj;
            }
            
            return _result.getRetDerivedClassResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructS1
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name retStructS1(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name inStructS1)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructS1_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1 _myRetStructS1 = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1();
            _myRetStructS1.setInStructS1(inStructS1);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructS1_RetStructS1_QNAME);
            _bodyBlock.setValue(_myRetStructS1);
            _bodyBlock.setSerializer(ns1_myRetStructS1_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetStructS1");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1Response _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1Response)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1Response)_responseObj;
            }
            
            return _result.getRetStructS1Result();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayString2D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring retArrayString2D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring inArrayString2D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayString2D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2D _myRetArrayString2D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2D();
            _myRetArrayString2D.setInArrayString2D(inArrayString2D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayString2D_RetArrayString2D_QNAME);
            _bodyBlock.setValue(_myRetArrayString2D);
            _bodyBlock.setSerializer(ns1_myRetArrayString2D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayString2D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2DResponse)_responseObj;
            }
            
            return _result.getRetArrayString2DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArray1D_SN
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson retArray1D_SN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson inArray1D_SN)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArray1D_SN_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SN _myRetArray1D_SN = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SN();
            _myRetArray1D_SN.setInArray1D_SN(inArray1D_SN);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArray1D_SN_RetArray1D_SN_QNAME);
            _bodyBlock.setValue(_myRetArray1D_SN);
            _bodyBlock.setSerializer(ns1_myRetArray1D_SN_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArray1D_SN");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SNResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SNResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SNResponse)_responseObj;
            }
            
            return _result.getRetArray1D_SNResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayString1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring retArrayString1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring inArrayString1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayString1D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1D _myRetArrayString1D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1D();
            _myRetArrayString1D.setInArrayString1D(inArrayString1D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayString1D_RetArrayString1D_QNAME);
            _bodyBlock.setValue(_myRetArrayString1D);
            _bodyBlock.setSerializer(ns1_myRetArrayString1D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayString1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1DResponse)_responseObj;
            }
            
            return _result.getRetArrayString1DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayAnyType1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType retArrayAnyType1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType inArrayAnyType1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayAnyType1D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1D _myRetArrayAnyType1D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1D();
            _myRetArrayAnyType1D.setInArrayAnyType1D(inArrayAnyType1D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayAnyType1D_RetArrayAnyType1D_QNAME);
            _bodyBlock.setValue(_myRetArrayAnyType1D);
            _bodyBlock.setSerializer(ns1_myRetArrayAnyType1D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayAnyType1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1DResponse)_responseObj;
            }
            
            return _result.getRetArrayAnyType1DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructSNSAS
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group retStructSNSAS(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group inStructSNSAS)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSNSAS_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAS _myRetStructSNSAS = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAS();
            _myRetStructSNSAS.setInStructSNSAS(inStructSNSAS);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSAS_RetStructSNSAS_QNAME);
            _bodyBlock.setValue(_myRetStructSNSAS);
            _bodyBlock.setSerializer(ns1_myRetStructSNSAS_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetStructSNSAS");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSASResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSASResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSASResponse)_responseObj;
            }
            
            return _result.getRetStructSNSASResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retEnumInt
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet retEnumInt(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet inEnumInt)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetEnumInt_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumInt _myRetEnumInt = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumInt();
            _myRetEnumInt.setInEnumInt(inEnumInt);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetEnumInt_RetEnumInt_QNAME);
            _bodyBlock.setValue(_myRetEnumInt);
            _bodyBlock.setSerializer(ns1_myRetEnumInt_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetEnumInt");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumIntResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumIntResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumIntResponse)_responseObj;
            }
            
            return _result.getRetEnumIntResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retStructSNSA
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee retStructSNSA(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetStructSNSA_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSA _myRetStructSNSA = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSA();
            _myRetStructSNSA.setInStructSNSA(inStructSNSA);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSA_RetStructSNSA_QNAME);
            _bodyBlock.setValue(_myRetStructSNSA);
            _bodyBlock.setSerializer(ns1_myRetStructSNSA_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetStructSNSA");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAResponse)_responseObj;
            }
            
            return _result.getRetStructSNSAResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayInt1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint retArrayInt1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint inArrayInt1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayInt1D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1D _myRetArrayInt1D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1D();
            _myRetArrayInt1D.setInArrayInt1D(inArrayInt1D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayInt1D_RetArrayInt1D_QNAME);
            _bodyBlock.setValue(_myRetArrayInt1D);
            _bodyBlock.setSerializer(ns1_myRetArrayInt1D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayInt1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1DResponse)_responseObj;
            }
            
            return _result.getRetArrayInt1DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayDecimal1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal retArrayDecimal1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal inArrayDecimal1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayDecimal1D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1D _myRetArrayDecimal1D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1D();
            _myRetArrayDecimal1D.setInArrayDecimal1D(inArrayDecimal1D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayDecimal1D_RetArrayDecimal1D_QNAME);
            _bodyBlock.setValue(_myRetArrayDecimal1D);
            _bodyBlock.setSerializer(ns1_myRetArrayDecimal1D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayDecimal1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1DResponse)_responseObj;
            }
            
            return _result.getRetArrayDecimal1DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retEnumString
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask retEnumString(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask inEnumString)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetEnumString_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumString _myRetEnumString = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumString();
            _myRetEnumString.setInEnumString(inEnumString);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetEnumString_RetEnumString_QNAME);
            _bodyBlock.setValue(_myRetEnumString);
            _bodyBlock.setSerializer(ns1_myRetEnumString_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetEnumString");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumStringResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumStringResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumStringResponse)_responseObj;
            }
            
            return _result.getRetEnumStringResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of retArrayDateTime1D
     */
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime retArrayDateTime1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime inArrayDateTime1D)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(RetArrayDateTime1D_OPCODE);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1D _myRetArrayDateTime1D = new org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1D();
            _myRetArrayDateTime1D.setInArrayDateTime1D(inArrayDateTime1D);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_RetArrayDateTime1D_RetArrayDateTime1D_QNAME);
            _bodyBlock.setValue(_myRetArrayDateTime1D);
            _bodyBlock.setSerializer(ns1_myRetArrayDateTime1D_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayDateTime1D");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1DResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1DResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1DResponse)_responseObj;
            }
            
            return _result.getRetArrayDateTime1DResult();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case RetStructSN_OPCODE:
                _deserialize_RetStructSN(bodyReader, deserializationContext, state);
                break;
            case RetDerivedClass_OPCODE:
                _deserialize_RetDerivedClass(bodyReader, deserializationContext, state);
                break;
            case RetStructS1_OPCODE:
                _deserialize_RetStructS1(bodyReader, deserializationContext, state);
                break;
            case RetArrayString2D_OPCODE:
                _deserialize_RetArrayString2D(bodyReader, deserializationContext, state);
                break;
            case RetArray1D_SN_OPCODE:
                _deserialize_RetArray1D_SN(bodyReader, deserializationContext, state);
                break;
            case RetArrayString1D_OPCODE:
                _deserialize_RetArrayString1D(bodyReader, deserializationContext, state);
                break;
            case RetArrayAnyType1D_OPCODE:
                _deserialize_RetArrayAnyType1D(bodyReader, deserializationContext, state);
                break;
            case RetStructSNSAS_OPCODE:
                _deserialize_RetStructSNSAS(bodyReader, deserializationContext, state);
                break;
            case RetEnumInt_OPCODE:
                _deserialize_RetEnumInt(bodyReader, deserializationContext, state);
                break;
            case RetStructSNSA_OPCODE:
                _deserialize_RetStructSNSA(bodyReader, deserializationContext, state);
                break;
            case RetArrayInt1D_OPCODE:
                _deserialize_RetArrayInt1D(bodyReader, deserializationContext, state);
                break;
            case RetArrayDecimal1D_OPCODE:
                _deserialize_RetArrayDecimal1D(bodyReader, deserializationContext, state);
                break;
            case RetEnumString_OPCODE:
                _deserialize_RetEnumString(bodyReader, deserializationContext, state);
                break;
            case RetArrayDateTime1D_OPCODE:
                _deserialize_RetArrayDateTime1D(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the RetStructSN operation.
     */
    private void _deserialize_RetStructSN(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetStructSNResponseObj =
            ns1_myRetStructSNResponse_LiteralSerializer.deserialize(ns1_RetStructSN_RetStructSNResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSN_RetStructSNResponse_QNAME);
        bodyBlock.setValue(myRetStructSNResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetDerivedClass operation.
     */
    private void _deserialize_RetDerivedClass(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetDerivedClassResponseObj =
            ns1_myRetDerivedClassResponse_LiteralSerializer.deserialize(ns1_RetDerivedClass_RetDerivedClassResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetDerivedClass_RetDerivedClassResponse_QNAME);
        bodyBlock.setValue(myRetDerivedClassResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructS1 operation.
     */
    private void _deserialize_RetStructS1(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetStructS1ResponseObj =
            ns1_myRetStructS1Response_LiteralSerializer.deserialize(ns1_RetStructS1_RetStructS1Response_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructS1_RetStructS1Response_QNAME);
        bodyBlock.setValue(myRetStructS1ResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayString2D operation.
     */
    private void _deserialize_RetArrayString2D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayString2DResponseObj =
            ns1_myRetArrayString2DResponse_LiteralSerializer.deserialize(ns1_RetArrayString2D_RetArrayString2DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayString2D_RetArrayString2DResponse_QNAME);
        bodyBlock.setValue(myRetArrayString2DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArray1D_SN operation.
     */
    private void _deserialize_RetArray1D_SN(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArray1D_SNResponseObj =
            ns1_myRetArray1D_SNResponse_LiteralSerializer.deserialize(ns1_RetArray1D_SN_RetArray1D_SNResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArray1D_SN_RetArray1D_SNResponse_QNAME);
        bodyBlock.setValue(myRetArray1D_SNResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayString1D operation.
     */
    private void _deserialize_RetArrayString1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayString1DResponseObj =
            ns1_myRetArrayString1DResponse_LiteralSerializer.deserialize(ns1_RetArrayString1D_RetArrayString1DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayString1D_RetArrayString1DResponse_QNAME);
        bodyBlock.setValue(myRetArrayString1DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayAnyType1D operation.
     */
    private void _deserialize_RetArrayAnyType1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayAnyType1DResponseObj =
            ns1_myRetArrayAnyType1DResponse_LiteralSerializer.deserialize(ns1_RetArrayAnyType1D_RetArrayAnyType1DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayAnyType1D_RetArrayAnyType1DResponse_QNAME);
        bodyBlock.setValue(myRetArrayAnyType1DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructSNSAS operation.
     */
    private void _deserialize_RetStructSNSAS(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetStructSNSASResponseObj =
            ns1_myRetStructSNSASResponse_LiteralSerializer.deserialize(ns1_RetStructSNSAS_RetStructSNSASResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSAS_RetStructSNSASResponse_QNAME);
        bodyBlock.setValue(myRetStructSNSASResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetEnumInt operation.
     */
    private void _deserialize_RetEnumInt(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetEnumIntResponseObj =
            ns1_myRetEnumIntResponse_LiteralSerializer.deserialize(ns1_RetEnumInt_RetEnumIntResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetEnumInt_RetEnumIntResponse_QNAME);
        bodyBlock.setValue(myRetEnumIntResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetStructSNSA operation.
     */
    private void _deserialize_RetStructSNSA(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetStructSNSAResponseObj =
            ns1_myRetStructSNSAResponse_LiteralSerializer.deserialize(ns1_RetStructSNSA_RetStructSNSAResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetStructSNSA_RetStructSNSAResponse_QNAME);
        bodyBlock.setValue(myRetStructSNSAResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayInt1D operation.
     */
    private void _deserialize_RetArrayInt1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayInt1DResponseObj =
            ns1_myRetArrayInt1DResponse_LiteralSerializer.deserialize(ns1_RetArrayInt1D_RetArrayInt1DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayInt1D_RetArrayInt1DResponse_QNAME);
        bodyBlock.setValue(myRetArrayInt1DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayDecimal1D operation.
     */
    private void _deserialize_RetArrayDecimal1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayDecimal1DResponseObj =
            ns1_myRetArrayDecimal1DResponse_LiteralSerializer.deserialize(ns1_RetArrayDecimal1D_RetArrayDecimal1DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayDecimal1D_RetArrayDecimal1DResponse_QNAME);
        bodyBlock.setValue(myRetArrayDecimal1DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetEnumString operation.
     */
    private void _deserialize_RetEnumString(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetEnumStringResponseObj =
            ns1_myRetEnumStringResponse_LiteralSerializer.deserialize(ns1_RetEnumString_RetEnumStringResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetEnumString_RetEnumStringResponse_QNAME);
        bodyBlock.setValue(myRetEnumStringResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the RetArrayDateTime1D operation.
     */
    private void _deserialize_RetArrayDateTime1D(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRetArrayDateTime1DResponseObj =
            ns1_myRetArrayDateTime1DResponse_LiteralSerializer.deserialize(ns1_RetArrayDateTime1D_RetArrayDateTime1DResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_RetArrayDateTime1D_RetArrayDateTime1DResponse_QNAME);
        bodyBlock.setValue(myRetArrayDateTime1DResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    protected java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myRetArrayInt1D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1D.class, ns1_RetArrayInt1D_TYPE_QNAME);
        ns1_myRetArray1D_SN_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SN.class, ns1_RetArray1D_SN_TYPE_QNAME);
        ns1_myRetStructSNSASResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSASResponse.class, ns1_RetStructSNSASResponse_TYPE_QNAME);
        ns1_myRetEnumStringResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumStringResponse.class, ns1_RetEnumStringResponse_TYPE_QNAME);
        ns1_myRetEnumInt_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumInt.class, ns1_RetEnumInt_TYPE_QNAME);
        ns1_myRetStructSN_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSN.class, ns1_RetStructSN_TYPE_QNAME);
        ns1_myRetDerivedClassResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClassResponse.class, ns1_RetDerivedClassResponse_TYPE_QNAME);
        ns1_myRetArrayString2D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2D.class, ns1_RetArrayString2D_TYPE_QNAME);
        ns1_myRetArrayString1D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1D.class, ns1_RetArrayString1D_TYPE_QNAME);
        ns1_myRetArrayAnyType1D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1D.class, ns1_RetArrayAnyType1D_TYPE_QNAME);
        ns1_myRetArray1D_SNResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArray1D_SNResponse.class, ns1_RetArray1D_SNResponse_TYPE_QNAME);
        ns1_myRetArrayDateTime1D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1D.class, ns1_RetArrayDateTime1D_TYPE_QNAME);
        ns1_myRetEnumIntResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumIntResponse.class, ns1_RetEnumIntResponse_TYPE_QNAME);
        ns1_myRetArrayAnyType1DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayAnyType1DResponse.class, ns1_RetArrayAnyType1DResponse_TYPE_QNAME);
        ns1_myRetStructS1_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1.class, ns1_RetStructS1_TYPE_QNAME);
        ns1_myRetStructS1Response_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructS1Response.class, ns1_RetStructS1Response_TYPE_QNAME);
        ns1_myRetArrayDecimal1DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1DResponse.class, ns1_RetArrayDecimal1DResponse_TYPE_QNAME);
        ns1_myRetArrayInt1DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayInt1DResponse.class, ns1_RetArrayInt1DResponse_TYPE_QNAME);
        ns1_myRetStructSNSA_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSA.class, ns1_RetStructSNSA_TYPE_QNAME);
        ns1_myRetArrayString1DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString1DResponse.class, ns1_RetArrayString1DResponse_TYPE_QNAME);
        ns1_myRetStructSNSAResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAResponse.class, ns1_RetStructSNSAResponse_TYPE_QNAME);
        ns1_myRetDerivedClass_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetDerivedClass.class, ns1_RetDerivedClass_TYPE_QNAME);
        ns1_myRetArrayDecimal1D_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDecimal1D.class, ns1_RetArrayDecimal1D_TYPE_QNAME);
        ns1_myRetStructSNSAS_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNSAS.class, ns1_RetStructSNSAS_TYPE_QNAME);
        ns1_myRetEnumString_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetEnumString.class, ns1_RetEnumString_TYPE_QNAME);
        ns1_myRetArrayString2DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayString2DResponse.class, ns1_RetArrayString2DResponse_TYPE_QNAME);
        ns1_myRetArrayDateTime1DResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetArrayDateTime1DResponse.class, ns1_RetArrayDateTime1DResponse_TYPE_QNAME);
        ns1_myRetStructSNResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.RetStructSNResponse.class, ns1_RetStructSNResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://tempuri.org/", "BasicHttpBinding_IComplexDataTypesDocLitW");
    private static final int RetStructSN_OPCODE = 0;
    private static final int RetDerivedClass_OPCODE = 1;
    private static final int RetStructS1_OPCODE = 2;
    private static final int RetArrayString2D_OPCODE = 3;
    private static final int RetArray1D_SN_OPCODE = 4;
    private static final int RetArrayString1D_OPCODE = 5;
    private static final int RetArrayAnyType1D_OPCODE = 6;
    private static final int RetStructSNSAS_OPCODE = 7;
    private static final int RetEnumInt_OPCODE = 8;
    private static final int RetStructSNSA_OPCODE = 9;
    private static final int RetArrayInt1D_OPCODE = 10;
    private static final int RetArrayDecimal1D_OPCODE = 11;
    private static final int RetEnumString_OPCODE = 12;
    private static final int RetArrayDateTime1D_OPCODE = 13;
    private static final javax.xml.namespace.QName ns1_RetStructSN_RetStructSN_QNAME = new QName("http://tempuri.org/", "RetStructSN");
    private static final javax.xml.namespace.QName ns1_RetStructSN_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSN");
    private CombinedSerializer ns1_myRetStructSN_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSN_RetStructSNResponse_QNAME = new QName("http://tempuri.org/", "RetStructSNResponse");
    private static final javax.xml.namespace.QName ns1_RetStructSNResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSNResponse");
    private CombinedSerializer ns1_myRetStructSNResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDerivedClass_RetDerivedClass_QNAME = new QName("http://tempuri.org/", "RetDerivedClass");
    private static final javax.xml.namespace.QName ns1_RetDerivedClass_TYPE_QNAME = new QName("http://tempuri.org/", "RetDerivedClass");
    private CombinedSerializer ns1_myRetDerivedClass_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetDerivedClass_RetDerivedClassResponse_QNAME = new QName("http://tempuri.org/", "RetDerivedClassResponse");
    private static final javax.xml.namespace.QName ns1_RetDerivedClassResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetDerivedClassResponse");
    private CombinedSerializer ns1_myRetDerivedClassResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructS1_RetStructS1_QNAME = new QName("http://tempuri.org/", "RetStructS1");
    private static final javax.xml.namespace.QName ns1_RetStructS1_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructS1");
    private CombinedSerializer ns1_myRetStructS1_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructS1_RetStructS1Response_QNAME = new QName("http://tempuri.org/", "RetStructS1Response");
    private static final javax.xml.namespace.QName ns1_RetStructS1Response_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructS1Response");
    private CombinedSerializer ns1_myRetStructS1Response_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString2D_RetArrayString2D_QNAME = new QName("http://tempuri.org/", "RetArrayString2D");
    private static final javax.xml.namespace.QName ns1_RetArrayString2D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayString2D");
    private CombinedSerializer ns1_myRetArrayString2D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString2D_RetArrayString2DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayString2DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayString2DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayString2DResponse");
    private CombinedSerializer ns1_myRetArrayString2DResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArray1D_SN_RetArray1D_SN_QNAME = new QName("http://tempuri.org/", "RetArray1D_SN");
    private static final javax.xml.namespace.QName ns1_RetArray1D_SN_TYPE_QNAME = new QName("http://tempuri.org/", "RetArray1D_SN");
    private CombinedSerializer ns1_myRetArray1D_SN_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArray1D_SN_RetArray1D_SNResponse_QNAME = new QName("http://tempuri.org/", "RetArray1D_SNResponse");
    private static final javax.xml.namespace.QName ns1_RetArray1D_SNResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArray1D_SNResponse");
    private CombinedSerializer ns1_myRetArray1D_SNResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString1D_RetArrayString1D_QNAME = new QName("http://tempuri.org/", "RetArrayString1D");
    private static final javax.xml.namespace.QName ns1_RetArrayString1D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayString1D");
    private CombinedSerializer ns1_myRetArrayString1D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayString1D_RetArrayString1DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayString1DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayString1DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayString1DResponse");
    private CombinedSerializer ns1_myRetArrayString1DResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1D_RetArrayAnyType1D_QNAME = new QName("http://tempuri.org/", "RetArrayAnyType1D");
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayAnyType1D");
    private CombinedSerializer ns1_myRetArrayAnyType1D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1D_RetArrayAnyType1DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayAnyType1DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayAnyType1DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayAnyType1DResponse");
    private CombinedSerializer ns1_myRetArrayAnyType1DResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSAS_RetStructSNSAS_QNAME = new QName("http://tempuri.org/", "RetStructSNSAS");
    private static final javax.xml.namespace.QName ns1_RetStructSNSAS_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSNSAS");
    private CombinedSerializer ns1_myRetStructSNSAS_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSAS_RetStructSNSASResponse_QNAME = new QName("http://tempuri.org/", "RetStructSNSASResponse");
    private static final javax.xml.namespace.QName ns1_RetStructSNSASResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSNSASResponse");
    private CombinedSerializer ns1_myRetStructSNSASResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumInt_RetEnumInt_QNAME = new QName("http://tempuri.org/", "RetEnumInt");
    private static final javax.xml.namespace.QName ns1_RetEnumInt_TYPE_QNAME = new QName("http://tempuri.org/", "RetEnumInt");
    private CombinedSerializer ns1_myRetEnumInt_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumInt_RetEnumIntResponse_QNAME = new QName("http://tempuri.org/", "RetEnumIntResponse");
    private static final javax.xml.namespace.QName ns1_RetEnumIntResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetEnumIntResponse");
    private CombinedSerializer ns1_myRetEnumIntResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSA_RetStructSNSA_QNAME = new QName("http://tempuri.org/", "RetStructSNSA");
    private static final javax.xml.namespace.QName ns1_RetStructSNSA_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSNSA");
    private CombinedSerializer ns1_myRetStructSNSA_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetStructSNSA_RetStructSNSAResponse_QNAME = new QName("http://tempuri.org/", "RetStructSNSAResponse");
    private static final javax.xml.namespace.QName ns1_RetStructSNSAResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetStructSNSAResponse");
    private CombinedSerializer ns1_myRetStructSNSAResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayInt1D_RetArrayInt1D_QNAME = new QName("http://tempuri.org/", "RetArrayInt1D");
    private static final javax.xml.namespace.QName ns1_RetArrayInt1D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayInt1D");
    private CombinedSerializer ns1_myRetArrayInt1D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayInt1D_RetArrayInt1DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayInt1DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayInt1DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayInt1DResponse");
    private CombinedSerializer ns1_myRetArrayInt1DResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1D_RetArrayDecimal1D_QNAME = new QName("http://tempuri.org/", "RetArrayDecimal1D");
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayDecimal1D");
    private CombinedSerializer ns1_myRetArrayDecimal1D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1D_RetArrayDecimal1DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayDecimal1DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayDecimal1DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayDecimal1DResponse");
    private CombinedSerializer ns1_myRetArrayDecimal1DResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumString_RetEnumString_QNAME = new QName("http://tempuri.org/", "RetEnumString");
    private static final javax.xml.namespace.QName ns1_RetEnumString_TYPE_QNAME = new QName("http://tempuri.org/", "RetEnumString");
    private CombinedSerializer ns1_myRetEnumString_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetEnumString_RetEnumStringResponse_QNAME = new QName("http://tempuri.org/", "RetEnumStringResponse");
    private static final javax.xml.namespace.QName ns1_RetEnumStringResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetEnumStringResponse");
    private CombinedSerializer ns1_myRetEnumStringResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1D_RetArrayDateTime1D_QNAME = new QName("http://tempuri.org/", "RetArrayDateTime1D");
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1D_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayDateTime1D");
    private CombinedSerializer ns1_myRetArrayDateTime1D_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1D_RetArrayDateTime1DResponse_QNAME = new QName("http://tempuri.org/", "RetArrayDateTime1DResponse");
    private static final javax.xml.namespace.QName ns1_RetArrayDateTime1DResponse_TYPE_QNAME = new QName("http://tempuri.org/", "RetArrayDateTime1DResponse");
    private CombinedSerializer ns1_myRetArrayDateTime1DResponse_LiteralSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://tempuri.org/"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
