/*
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org.
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.xop.doclit;

import javax.activation.DataHandler;


public class  PingMsgResponse
{
   protected DataHandler xopContent;

   public PingMsgResponse(){
   }

   public PingMsgResponse(DataHandler dataHandler) {
      this.xopContent = dataHandler;
   }

   public DataHandler getXopContent() {
      return xopContent;
   }

   public void setXopContent(DataHandler xopContent) {
      this.xopContent = xopContent;
   }
}
