/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.xop.doclit;

import javax.activation.DataHandler;

public class PingMsg
{
   protected String message;
   protected DataHandler xopContent;

   public PingMsg(){}

   public PingMsg(String message, DataHandler dataHandler){
      this.message=message;
      this.xopContent = dataHandler;
   }

   public java.lang.String getMessage() { return message ;}

   public void setMessage(java.lang.String message){ this.message=message; }

   public DataHandler getXopContent() {
      return xopContent;
   }

   public void setXopContent(DataHandler xopContent) {
      this.xopContent = xopContent;
   }
}
