/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.xop.doclit;


import javax.xml.rpc.ServiceException;


public interface  TestService_Service extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.xop.doclit.TestService_PortType getTestServicePort() throws ServiceException;

}
