// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class BaseDataTypesDocLitWService_Impl extends com.sun.xml.rpc.client.BasicService implements BaseDataTypesDocLitWService {
    private static final QName serviceName = new QName("http://tempuri.org/", "BaseDataTypesDocLitWService");
    private static final QName ns1_BasicHttpBinding_IBaseDataTypesDocLitW_QNAME = new QName("http://tempuri.org/", "BasicHttpBinding_IBaseDataTypesDocLitW");
    private static final Class IBaseDataTypesDocLitW_PortClass = org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.IBaseDataTypesDocLitW.class;
    
    public BaseDataTypesDocLitWService_Impl() {
        super(serviceName, new QName[] {
                        ns1_BasicHttpBinding_IBaseDataTypesDocLitW_QNAME
                    },
            new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.BaseDataTypesDocLitWService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_BasicHttpBinding_IBaseDataTypesDocLitW_QNAME) &&
                serviceDefInterface.equals(IBaseDataTypesDocLitW_PortClass)) {
                return getBasicHttpBinding_IBaseDataTypesDocLitW();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(IBaseDataTypesDocLitW_PortClass)) {
                return getBasicHttpBinding_IBaseDataTypesDocLitW();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.IBaseDataTypesDocLitW getBasicHttpBinding_IBaseDataTypesDocLitW() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_BasicHttpBinding_IBaseDataTypesDocLitW_QNAME));
        handlerChain.setRoles(roles);
        org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.IBaseDataTypesDocLitW_Stub stub = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW.IBaseDataTypesDocLitW_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
