// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class IBaseDataTypesRpcLit_RetUShort_ResponseStruct_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_RetUShortResult_QNAME = new QName("", "RetUShortResult");
    private static final javax.xml.namespace.QName ns2_unsignedShort_TYPE_QNAME = SchemaConstants.QNAME_TYPE_UNSIGNED_SHORT;
    private CombinedSerializer ns2_myns2_unsignedShort__int_UnsignedShort_Serializer;
    
    public IBaseDataTypesRpcLit_RetUShort_ResponseStruct_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public IBaseDataTypesRpcLit_RetUShort_ResponseStruct_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myns2_unsignedShort__int_UnsignedShort_Serializer = (CombinedSerializer)registry.getSerializer("", int.class, ns2_unsignedShort_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct instance = new org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_RetUShortResult_QNAME)) {
                member = ns2_myns2_unsignedShort__int_UnsignedShort_Serializer.deserialize(ns1_RetUShortResult_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setRetUShortResult(((java.lang.Integer)member).intValue());
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_RetUShortResult_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct instance = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct instance = (org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service.IBaseDataTypesRpcLit_RetUShort_ResponseStruct)obj;
        
        if (new java.lang.Integer(instance.getRetUShortResult()) == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns2_myns2_unsignedShort__int_UnsignedShort_Serializer.serialize(new java.lang.Integer(instance.getRetUShortResult()), ns1_RetUShortResult_QNAME, null, writer, context);
    }
}
